{% set name = "cspice" %}
{% set version = "66" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../../cspice
  
#  patches:
#    - 0001-patch-for-n66-dskx02.c.patch  # [not win]
#    - 0002-patch-for-n66-subpnt.c.patch  # [not win]
#    - 0001-patch-for-n66-dskx02.c-windows.patch  # [win]
#    - 0002-patch-for-n66-subpnt.c-windows.patch  # [win]
#    - 0003_remove_m64_linux.patch  # [linux64 or aarch64]
#    - 0003_remove_m64_osx.patch  # [osx]
#    - 0004_inquire_unistd.patch  # [osx]

build:
  number: 1014

requirements:
  build:
    - {{ compiler('c') }}
    - tcsh  # [not win]
    - parallel

test:
  requires:
    - {{ compiler('c') }}

  files:
    - test_cspice.c
  
  commands:
# Tools haven't been converted, so they won't work.
#    - "version" 
#    - "chronos"
    - "$CC test_cspice.c -I$PREFIX/include -L$PREFIX/lib -lcspice -o test_cspice"  # [not win]
    - "LD_LIBRARY_PATH=$PREFIX/lib ./test_cspice"  # [not win] 

#  downstreams:
#    - mechsoft::spiceypy  # [not win]

about:
  home: https://naif.jpl.nasa.gov/naif/toolkit.html
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'NASA ancillary information system'

  description: |
      SPICE is an ancillary information system that provides scientists and
      engineers the capability to include space geometry and event data into
      mission design, science observation planning, and science data analysis
      software.
  doc_url: https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/index.html

extra:
  recipe-maintainers:
    - astrojuanlu
    - AndrewAnnex
